### ISSUE TITLE
Handshake Error (amazon ebs)

### ISSUE THREAD

**Issue by msuzoagu** [hashicorp/packer-plugin-amazon#386] opened 2023-05-13 14:13 UTC
#### Overview of the Issue

When attempting to build ami, provisioning step fails with error message `failed to handshake` even though ssh connection has been made.   

#### Reproduction Steps

- PACKER_LOG=1 packer build [simple packer template](https://gist.github.com/msuzoagu/ba79fc355190b5793a27c8a472093976)  

### Plugin and Packer version

- Packer v1.8.7
- Packer-Plugin-Amazon v1.2.5

### Simplified Packer Buildfile

- [simple packer template](https://gist.github.com/msuzoagu/ba79fc355190b5793a27c8a472093976)

### Operating system and Environment details

Local Machine: macOS Ventura

Remote:
  - `aws_name = "ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20230325"`
  - `ami_id              = "ami-0a695f0d95cefc163"`
  - `ami_owners          = ["099720109477"]`
  - `ssh_username        = "ubuntu"`

### Log Fragments and crash.log files

- [handshake error surfaced without `ANSIBLE_STDOUT_CALLBACK=debug`](https://gist.github.com/msuzoagu/01f9158f6beb2518385bbab9987a8839)
- [file transfer error surfaced with `ANSIBLE_STDOUT_CALLBACK=debug`](https://gist.github.com/msuzoagu/be1003f765a94f5388598a01ca03af54)

**Comment by msuzoagu** [comment] 2023-05-16 13:47
see [workaround](https://github.com/hashicorp/packer-plugin-ansible/issues/155#issuecomment-1549677028)

**Comment by lbajolet-hashicorp** [comment] 2023-05-26 20:41
Hi @msuzoagu,

I can't access your gist for the template you're trying to run this build on, could you double check/re-share it?

From the logs it looks like you're using a proxy for Ansible to communicate with the instance, is that right? From what I can see, since your instance has a public IP, you probably don't need to, as the provisioner should be able to use that IP/Port to connect to your instance directly, could you try setting `use_proxy = false` in your Ansible config?

I'm not yet super familiar with the proxy adapter for Ansible, so I'd need to dig a bit deeper into this to understand what's happening here exactly, but I'll keep this updated.

**Comment by lbajolet-hashicorp** [comment] 2023-10-13 19:54
Closing as duplicate of https://github.com/hashicorp/packer/issues/12416

**Closed by lbajolet-hashicorp** 2023-10-13 19:54 UTC
Labels: bug
