### ISSUE TITLE
 Error modify AMI attributes: InvalidAMIAttributeItemValue: Invalid attribute item value ”

### ISSUE THREAD

**Issue by wkompally** [hashicorp/packer-plugin-amazon#186] opened 2022-01-26 21:39 UTC
When filing a bug, please include the following headings if possible. Any
example text in this template can be deleted.

#### Overview of the Issue
Hello,
I recently upgraded packer to version 1.7.6 and started getting this error. I had no issues before it was running without any issues 
#### Reproduction Steps
Using env variable 
{
  "variables": {
    "ami_users": "{{env `acct_list`}}"
  },
Steps to reproduce this issue

### Plugin and Packer version
--version 1.7.6
From `packer version`

### Simplified Packer Buildfile

If the file is longer than a few dozen lines, please include the URL to the
[gist](https://gist.github.com/) of the log or use the [Github detailed
format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d)
instead of posting it directly in the issue.

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.

### Log Fragments and crash.log files

Include appropriate log fragments. If the log is longer than a few dozen lines,
please include the URL to the [gist](https://gist.github.com/) of the log or
use the [Github detailed format](https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d) instead of posting it directly in the issue.

Set the env var `PACKER_LOG=1` for maximum log detail.

**Comment by nywilken** [comment] 2022-01-27 01:21
Hi @wkompally thanks for opening up this issue. Can you please provide a copy of the build template with any sensitive information removed. I see that you are using the `env` function to get a list of account user ids.

Have you tried hard coding in the value of the of the environment variable acct_list`?

I would expect to see the value that was read in for "ami_users" in the error message. I tested with 1.7.6 and the latest version of Packer was not able to reproduce this issue.  I tested reading from the environment variable a single value and hardcoded a list of ami_users and things appear to work. But to get a better idea of what might be happening here it would be helpful to have  repro template and an example of what {{env `acct_list`}} is returning.

**Comment by wkompally** [comment] 2022-01-27 01:43
Hi @nywilken I tried coding in the value with one account number and it works but when I do the env variable it is failing with this 
machine readable: error-count []string{"1"}
**==> Some builds didn't complete successfully and had errors:
2022/01/26 20:33:47 machine readable: amazon-ebs,error []string{"Error modify AMI attributes: InvalidAMIAttributeItemValue: Invalid attribute item value \"**

`{
  "variables": {
    "ami_users": "{{env `acct_list`}}"
  },
  "builders":
  [
    {
      "type": "amazon-ebs",
      "ssh_keypair_name": "",
      "ssh_private_key_file": "",
      "region": "us-east-1",
      "availability_zone": "us-east-1a",
      "instance_type": "t2.medium",
      "ssh_username": "ec2-user",
      "ssh_timeout": "10m",
      "disable_stop_instance": false,
      "ami_name": "TEST",
      "ami_users": "{{ user `ami_users` }}",
      "snapshot_users": "{{user `ami_users`}}",
      "ami_description": "AMI built with packer",
      "tags":
      {
        "OS": "Linux",
        "OS_Version": "RHEL",
        "source_ami": "{{ .SourceAMI }}",
        "CreationDate": "{{isotime \"2006-01-02T15:04:05.000Z\"}}"
      },`

Thanks,
Wilson

**Comment by wkompally** [comment] 2022-01-28 20:30
Hi @nywilken just want to touch base to see if you need any additional information.

**Comment by nywilken** [comment] 2022-01-28 21:10
hi @wkompally thanks for the template and your follow up response. I got caught up in few other things and wasn't able to get back to you immediately. 

That said, given your ability to run a successful build by hard coding the value seems to imply that the issue is around reading the value of "{{env \`acct_list\`}}". Which to be honest I don't know if that would work right out the box because the expected value for the `ami_users` is meant to be a slice of strings or `["abc", "def", "..."]`. The JSON template will read that value as a string. Unless you are escaping the quotes and square brackets. 

Can you give me an example of the value of acct_list, and maybe show me how you are setting the value before running `packer build`?


Below is an example of what I think you are trying to do. I say think because I don't know the value of your environment variable. But if I am correct I would recommend using HCL2 for the template to achieve your goal. 

```hcl
variable "source_list" {
  default =  env("ACCT_LIST")
  }

local "sources_list" {
  expression = split(",", var.source_list)
}


source "null" "example" {
  communicator = "none"
}

source "null" "example2" {
  communicator = "none"
}


build {
  sources = local.sources_list

  provisioner "shell-local" {
    inline = ["echo local value is ${source.name}"]
  }
}
```

I create a variable that I read from an environment variable. The value is a comma separated string. After I read in the value I convert the string into a list type which I can then assign to the sources argument which expects a list. This is similar to the ami_users argument for the amazon-ebs builder. I can change the value of ACCT_LIST and have it read in properly. 

Example with two sources
```
~>  ACCT_LIST="source.null.example,source.null.example2" packer build /tmp/source.pkr.hcl
null.example: output will be in this color.
null.example2: output will be in this color.

==> null.example2: Running local shell script: /var/folders/_9/_q1cqjtd3358p1ldhy7j399m0000gn/T/packer-shell314087302
==> null.example: Running local shell script: /var/folders/_9/_q1cqjtd3358p1ldhy7j399m0000gn/T/packer-shell3636737960
    null.example: local value is example
Build 'null.example' finished after 44 milliseconds 377 microseconds.
    null.example2: local value is example2
Build 'null.example2' finished after 89 milliseconds 758 microseconds.

==> Wait completed after 89 milliseconds 791 microseconds

==> Builds finished. The artifacts of successful builds are:
--> null.example: Did not export anything. This is the null builder
--> null.example2: Did not export anything. This is the null builder
```

Example with just one source value
```
~>  ACCT_LIST="source.null.example" packer build /tmp/source.pkr.hcl
null.example: output will be in this color.

==> null.example: Running local shell script: /var/folders/_9/_q1cqjtd3358p1ldhy7j399m0000gn/T/packer-shell4245429305
    null.example: local value is example
Build 'null.example' finished after 171 milliseconds 48 microseconds.

==> Wait completed after 171 milliseconds 94 microseconds

==> Builds finished. The artifacts of successful builds are:
--> null.example: Did not export anything. This is the null builder
```

**Comment by wkompally** [comment] 2022-01-28 22:42
Thank @nywilken 

I have a python script that gets the list of accounts and stores in an env variable
Here's the list before calling
Do I have to change the format to look like this ["abc", "def", "..."] but in my previous version before 1.7.6 I have the format like this

123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 

But after calling the packer it is giving me this

machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2022/01/27 11:42:43 machine readable: amazon-ebs,error []string{"Error modify AMI attributes: InvalidAMIAttributeItemValue: Invalid attribute item value \" 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx  \" for userId item type.\n\tstatus code:

Is it because I am still using json instead of HCL?

**Comment by nywilken** [comment] 2022-01-29 13:55
@wkompally thanks for the additional error information and example value. It helps a lot. 

>  Is it because I am still using json instead of HCL?

No, the code for JSON and HCL2 work the same way when making the request to AWS. I mentioned HCL2 because it does give a bit more flexibility in formatting variables to convert them to the expected types. When you move to HCL2 argument types will be enforced so you will no longer be able to just pass a string to `ami_users`.  

> Do I have to change the format to look like this ["abc", "def", "..."] but in my previous version before 1.7.6 I have the format like this

For my test JSON template I found that setting my environment variable to `ACCT_LIST="abc,def,ghi"` a comma separate string with no brackets the build succeeds as expected and the appropriate user permissions are assigned to the resulting AMI. This is because Packer knows to convert this JSON comma separated list into a slice of strings (this is an implementation detail). 

Setting the  environment variable to `ACCT_LIST="abc def ghi"` (space separated) like in your example my build results in the same error that you are seeing. Since this worked for you previously I do wonder if there was some change to the SDK or upstream API that no longer supports this format. I have not found any information on this yet. 

That said, if you try re-running the build with the version of Packer you were using previously do you run into any issues? 

I looked at the code base that handles the ModifyImageAttribute call and found no direct changes to how we process the value of `ami_users`. To get a better idea if there were any changes elsewhere that might be causing this change in behavior in the Packer code base I would need to know the version that you were using previously, if it still works for you. 

Lastly, looking at the error messaging you provided it appears that you list of accounts contains a space at the beginning of the string which would also cause issues. If the space was added in formatting for sharing on this issue you can ignore this comment. 

```
InvalidAMIAttributeItemValue: Invalid attribute item value " 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx 123456789xxx " for userId item type.\n\tstatus code:```

I know this is a bit of information so please let me know if you have any questions or if something is not clear.

**Comment by wkompally** [comment] 2022-01-31 03:12
Hi @nywilken 

Thanks for taking time and answering all my questions.

I made some changes and converted the list to a comma separated like 123,123,123 without any double quotes and it worked :)

I really appreciate all the help 

Thanks,
∑ilson

**Comment by nywilken** [comment] 2022-02-03 14:59
@wkompally glad to help, and I'm glad to hear that you were able to get into a working state. I'm going to close this issue. But if you find that you are running into any further issues when switching over to HCL don't hesitate to reach out.

**Closed by nywilken** 2022-02-03 14:59 UTC
Labels: bug, waiting-reply

**Comment by wkompally** [comment] 2022-02-03 15:01
@nywilken I am having issues switching over to HCL after upgrading I got these lines
source "amazon-ebs" "**autogenerated_1**"
source_ami = "${data.amazon-ami.autogenerated_1.id}"
build {
sources = ["s source "amazon-ebs" "autogenerated_1"
source_ami = "${data.amazon-ami.autogenerated_1.id}"
build {
sources = ["**source.amazon-ebs.autogenerated_1**"]

what should be replaced with autogenerated if I am building a rhel ami?

**Comment by nywilken** [comment] 2022-02-03 15:48
@wkompally it is hard to make out exactly what your template looks like after running hcl2_upgrade with the provided snippet.

Are you able to share the template? 

quickly looking at the provided snippet I see that a datasource is being used so I would recommend checking out the documentation for the datasource [here](https://www.packer.io/plugins/datasources/amazon/ami). The datasource is where you would set the details for the RHEL ami. 

Here is an example of a working HCL template that might help

```
variables {
  virtualization-type = "hvm"
  name                = "Windows_Server-2016-English-Full-Base-*"
  root-device-type    = "ebs"
  most_recent         = true
}

data "amazon-ami" "test" {
  filters = {
    virtualization-type = var.virtualization-type
    name                = var.name
    root-device-type    = var.root-device-type
  }
  most_recent = var.most_recent
  owners      = ["801119661308"]
}

locals { source_ami = data.amazon-ami.test.id }

source "amazon-ebs" "basic-example" {
  user_data_file = "files/configure-source-ssh.ps1"
  source_ami     = "${data.amazon-ami.test.id}"
  instance_type  = "t2.small"
  ssh_agent_auth = false
  ami_name       = "packer_AWS {{timestamp}}"
  communicator   = "ssh"
  ssh_timeout    = "10m"
  ssh_username   = "Administrator"
}

build {
  sources = [
    "source.amazon-ebs.basic-example"
  ]
}
```

**Comment by wkompally** [comment] 2022-02-03 15:59
Thanks @nywilken 
Yes, I can share the template

`# This file was autogenerated by the 'packer hcl2_upgrade' command. We
# recommend double checking that everything is correct before going forward. We
# also recommend treating this file as disposable. The HCL2 blocks in this
# file can be moved to other files. For example, the variable blocks could be
# moved to their own 'variables.pkr.hcl' file, etc. Those files need to be
# suffixed with '.pkr.hcl' to be visible to Packer. To use multiple files at
# once they also need to be in the same folder. 'packer inspect folder/'
# will describe to you what is in that folder.

# Avoid mixing go templating calls ( for example ```{{ upper(`string`) }}``` )
# and HCL2 calls (for example '${ var.string_value_example }' ). They won't be
# executed together and the outcome will be unknown.

# All generated input variables will be of 'string' type as this is how Packer JSON
# views them; you can change their type later on. Read the variables type
# constraints documentation
# https://www.packer.io/docs/templates/hcl_templates/variables#type-constraints for more info.
variable "ami_users" {
  type    = string
  default = "${env("acct_list")}"
}

# The amazon-ami data block is generated from your amazon builder source_ami_filter; a data
# from this block can be referenced in source and locals blocks.
# Read the documentation for data blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/data
# Read the documentation for the Amazon AMI Data Source here:
# https://www.packer.io/docs/datasources/amazon/ami
data "amazon-ami" "autogenerated_1" {
  filters = {
    architecture        = "x86_64"
    name                = "RHEL-7"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["3xxxx"]
  region      = "us-east-1"
}
# The "legacy_isotime" function has been provided for backwards compatability, but we recommend switching to the timestamp and formatdate functions.

# source blocks are generated from your builders; a source can be referenced in
# build blocks. A build block runs provisioner and post-processors on a
# source. Read the documentation for source blocks here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/source
source "amazon-ebs" "autogenerated_1" {
  ami_description       = "RHEL 7 AMI built with packer"
  ami_name              = "TEST"
  ami_users             = "${var.ami_users}"
  availability_zone     = "us-east-1a"
  disable_stop_instance = false
  instance_type         = "t2.medium"
  launch_block_device_mappings {
    delete_on_termination = "true"
    device_name           = "/dev/sda1"
    encrypted             = true
    kms_key_id            = ""
  }
  region = "us-east-1"
  run_tags = {
    Description                        = "Packer AMI builder"
    ostype                                = "linux"
    osver                                  = "RHEL7"
  }
  security_group_ids   = [""]
  snapshot_users       = "${var.ami_users}"
  source_ami           = "${data.amazon-ami.autogenerated_1.id}"
  ssh_keypair_name     = ""
  ssh_private_key_file = ""
  ssh_timeout          = "10m"
  ssh_username         = ""
  subnet_id            = ""
  tags = {
    CreationDate = "${legacy_isotime("2006-01-02T15:04:05.000Z")}"
    OS           = "Linux"
    OS_Version   = "RHEL 7.9"
    source_ami   = "{{ .SourceAMI }}"
  }
  vpc_id = ""
}

# a build block invokes sources and runs provisioning steps on them. The
# documentation for build blocks can be found here:
# https://www.packer.io/docs/templates/hcl_templates/blocks/build
build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    inline = []
  }

  provisioner "shell" {
    expect_disconnect = "true"
    pause_before      = "30s"
    script            = "scripts/test.sh"
  }

  provisioner "shell" {
    inline = []
  }

}
`
